Dict = {"COMANDO": "Com", "POMPA": "Pmp", "CIRCUITO": "Circ", "FAN": "F", "COIL": "C", "TEMPERATURA": "Temp",
        "STATO": "St", "VALVOLA": "Vlv", "PREPARATORE": "Prep", "PRIMARIO": "Prim", "APERTOSCATTATO": "ApScat",
        "CUMULATIVO": "Cumul", "APERTO": "Ap", "APERTI": "Ap", "CHIUSO": "Ch", "CHIUSI": "Ch", "CALDA": "C",
        "CALDO": "C", "FREDDA": "F", "FREDDO": "F", "SCAMBIATORE": "SC", "STADIO": "Stad", "BLOCCO": "Blocco",
        "GRUPPO": "Gr", "MANCANZA": "Manc", "MASSIMO": "Max", "MASSIMA": "Max", "Massimi": "Max", "SERBATOI": "Serb",
        "SERBATOIO": "Serb", "MINIMO": "Min", "MINIMA": "Min", "MINIMI": "Min", "SCATTATO": "Scat", "SCATTATI": "Scat",
        "TERMICO": "T", "TERMICA": "T", "UTILIZZO": "Utilizzo", "ACS": "ACS", "ARIA": "Ar", "CALDOFREDDO": "CF",
        "VENTILCONVETTORE": "VentilC", "VENTILCONVETTORI": "VentilC", "VENTILATORE": "Vt", "VENTILATORI": "Vt",
        "FREECOOLING": "FreeC", "FILTRO": "Filt", "FILTRI": "Filt", "NORD": "Nord", "SUD": "Sud", "MOBILI": "Mobil",
        "CENTRALE": "Centr", "CENTRALI": "Centr", "ANTINCENDIO": "Antinc", "CONTAPERSONE": "ContaP",
        "PROTEZIONI": "Protez", "INTERVENTO": "Interv", "INTERVENTI": "Interv", "CIRCUITI": "Circ", "AUSILIARI": "Aux",
        "AUSILIARE": "Aux", "SCARICATORE": "Scar", "SOVRATENS": "Sovra", "SERRANDA": "Serr", "SERRANDE": "Serr",
        "AUTOMATICO": "Auto", "AUTOMATICHE": "Auto", "SARACINESCHE": "Saracin", "SARACINESCA": "Saracin",
        "PRESENZA": "Pres", "PROTEZIONE": "Protez", "POMPE": "Pmp", "TENSIONE": "Tens", "CONTROLLO": "Contr",
        "CORRIDOIO": "Corr", "CORRIDOI": "Corr", "Energia": "Ener", "Insegna": "Inseg", "Insegne": "Inseg",
        "Spogliatoi": "Spogl", "Deposito": "Depos", "Depositi": "Depos", "SCALDANTE": "Scald", "SCALDANTI": "Scald",
        "SEZIONATORE": "Sezion", "SEZIONATORI": "Sezion", "RACK": "Rack"}
